# Generated by Django 3.1.3 on 2020-11-18 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20201118_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes',
            field=models.BooleanField(null=True),
        ),
    ]
