# Generated by Django 3.1.3 on 2020-11-20 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20201118_1413'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='downs',
        ),
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='post',
            name='ups',
        ),
    ]
