# Generated by Django 3.1.3 on 2020-11-20 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_upvoted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='ups',
            field=models.IntegerField(default=0),
        ),
    ]
