# Generated by Django 3.1.3 on 2020-11-20 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_ups'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='downs',
            field=models.IntegerField(default=0),
        ),
    ]
