# Generated by Django 3.1.3 on 2020-11-16 06:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('subreddits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subreddit',
            name='members',
            field=models.ManyToManyField(related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
    ]
