# Generated by Django 3.1.3 on 2020-11-16 14:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subreddits', '0002_subreddit_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subreddit',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
